### ISSUE TITLE
Convert the code to be written in TypeScript

### ISSUE THREAD

**Issue by jleung51** [pacmacro/pm-server-node#3]
TypeScript is a safe and well-designed language which transpiles to Javascript.

Resources on Typescript:

* [Official website](https://www.typescriptlang.org/)
* [Starter project with Express and TypeScript](https://www.typescriptlang.org/samples/)
* [Modifying a Node project to use TypeScript](https://developer.okta.com/blog/2018/11/15/node-express-typescript)

**Comment by whiitehead** [comment]
Hella done
