### ISSUE TITLE
Documentation: Moving the wiki over to this repo

### ISSUE THREAD

**Issue by whiitehead** [pacmacro/pm-server-node#39]
API documentation is currently found [here](https://github.com/pacmacro/pm-server-spring/wiki).

**Comment by ChicoRao** [comment]
https://github.com/darwin/move-wiki

Found this, but I am not sure how reliable this is

**Comment by jleung51** [comment]
Look into GitHub's wiki system - it's actually just a git repo. You can figure out how to clone the repo which represents the old wiki, and push that to the repo which represents the new wiki!

**Comment by aymansays** [comment]
Cannot seem to open this repo's wiki when I click on the "Wiki" tab. It simply redirects me back to the repo's homepage.

**Comment by jleung51** [comment]
Try now? I've created the initial page, maybe that's required by an admin.

https://github.com/pacmacro/pm-server-node/wiki

**Comment by aymansays** [comment]
I believe it's because I wasn't a collaborator to this project. But I manage to move the wiki over.
Thank you!
