### ISSUE TITLE
Update the readme

### ISSUE THREAD

**Issue by whiitehead** [pacmacro/pm-server-node#42]
It would be great to have some instructions about running the server -- even something about how to contribute or what dev tools to use.

**Comment by engichang1467** [comment]
I added some instructions for installing typescript on the setup section.

Take a look here:
https://github.com/engichang1467/pm-server-node/blob/master/README.md

If you're cool with it, then let me know when u want the pull request.

**Comment by engichang1467** [comment]
Already done the PR
