### ISSUE TITLE
Modify keys of location in database to match specification

### ISSUE THREAD

**Issue by jleung51** [pacmacro/pm-server-node#7]
**Description and Current Behavior**
Currently, the database uses values with the keys as `lon` and `lat` (see [example](https://github.com/pacmacro/pm-server-node/blob/7612eadf00ff72023e6ddc005a316b91d2673ed4/database.js#L9)).

**Expected Behavior**
The key names should match the API specification exactly so there is minimal data modification necessary. Here is a [sample format from the API documentation](https://github.com/pacmacro/pm-server/wiki/API-Documentation-for-Players#json-body-4).

**Comment by whiitehead** [comment]
done
